FROM python:3.10-bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV POETRY_VERSION 1.8.3

SHELL [ "/bin/bash", "-euxo", "pipefail", "-c" ]

RUN pip install poetry==$POETRY_VERSION && \
    poetry config virtualenvs.create false

WORKDIR /tmp

COPY pyproject.toml poetry.lock ./

RUN poetry install

WORKDIR /primerdriver

ENTRYPOINT [ "./docker-entrypoint.dev.sh" ]
