services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: kvdomingo/primerdriver-api:latest
    env_file: .env
    volumes:
      - .:/primerdriver
    ports:
      - '5000:5000'

  frontend:
    image: oven/bun:1.1-alpine
    environment:
      NODE_ENV: development
    entrypoint:
      - /bin/sh
      - "-c"
      - "bun install && exec bun run dev"
    working_dir: /web
    volumes:
      - ./ui:/web
    ports:
      - '3000:3000'
