FROM python:3.10-bullseye

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV POETRY_VERSION 1.3.2

RUN pip install poetry==$POETRY_VERSION && poetry config virtualenvs.create false

WORKDIR /tmp

COPY pyproject.toml poetry.lock ./

RUN poetry install

WORKDIR /primerdriver

ENTRYPOINT ["poetry", "run", "flask", "run", "-h", "0.0.0.0", "-p", "5000", "--reload"]
