version: '3'

env:
  NAME: primerdriver-dev
  SHORT_SHA:
    sh: git show --format="%h" --no-patch

tasks:
  default:
    cmds:
      - docker compose -p {{.NAME}} up -d --build --remove-orphans {{.CLI_ARGS}}
      - task logs

  logs:
    cmds:
      - docker compose -p {{.NAME}} logs --follow {{.CLI_ARGS}}

  shutdown:
    cmds:
      - docker compose -p {{.NAME}} stop {{.CLI_ARGS}}

  restart:
    cmds:
      - docker compose -p {{.NAME}} restart {{.CLI_ARGS}}

  reload-proxy:
    cmds:
      - docker compose -p {{.NAME}} exec -- proxy nginx -s reload

  clean:
    cmds:
      - docker compose -p {{.NAME}} down -v --remove-orphans
