version: '3'

env:
  NAME: primerdriver
  SHORT_SHA:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmds:
      - docker compose -p {{.NAME}} up -d --build --remove-orphans {{.CLI_ARGS}}

  logs:
    interactive: true
    cmds:
      - docker compose -p {{.NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    cmds:
      - docker compose -p {{.NAME}} stop {{.CLI_ARGS}}

  restart:
    cmds:
      - docker compose -p {{.NAME}} restart {{.CLI_ARGS}}

  reload-proxy:
    cmds:
      - docker compose -p {{.NAME}} exec -- proxy nginx -s reload

  clean:
    cmds:
      - docker compose -p {{.NAME}} down -v --remove-orphans
