version: '3'

env:
  NAME: primerdriver
  SHORT_SHA:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmd: docker compose -p {{.NAME}} up -d --build --remove-orphans {{.CLI_ARGS}}

  logs:
    interactive: true
    cmd: docker compose -p {{.NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    cmd: docker compose -p {{.NAME}} stop {{.CLI_ARGS}}

  restart:
    cmd: docker compose -p {{.NAME}} restart {{.CLI_ARGS}}

  reload-proxy:
    cmd: docker compose -p {{.NAME}} exec -- proxy nginx -s reload

  clean:
    cmd: docker compose -p {{.NAME}} down -v --remove-orphans

  build-cr:
    cmd: >
      docker build 
      -t kvdomingo/primerdriver-web:{{.SHORT_SHA}}
      -t kvdomingo/primerdriver-web:latest
      --build-arg SHORT_SHA={{.SHORT_SHA}}
      -f Dockerfile.prod .
